# Generated by Django 5.1.1 on 2024-09-29 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_studio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filial",
            name="activities",
        ),
        migrations.RemoveField(
            model_name="filial",
            name="coaches",
        ),
        migrations.RemoveField(
            model_name="filial",
            name="schedule",
        ),
        migrations.AddField(
            model_name="customuser",
            name="filial",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coaches",
                to="fitness_studio.filial",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="filial",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="fitness_studio.filial",
            ),
            preserve_default=False,
        ),
    ]
