# Generated by Django 5.1.1 on 2024-09-29 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "fitness_studio",
            "0002_remove_filial_activities_remove_filial_coaches_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activities",
            name="goals",
        ),
    ]
